const NPM_LICENSE_DB: Record<string, string> = {
  'lodash': 'MIT',
  'react': 'MIT',
  'react-dom': 'MIT',
  'vue': 'MIT',
  'express': 'MIT',
  'koa': 'MIT',
  'axios': 'MIT',
  'typescript': 'Apache-2.0',
  'webpack': 'MIT',
  'vite': 'MIT',
  'next': 'MIT',
  'nuxt': 'MIT',
  'angular': 'MIT',
  'jquery': 'MIT',
  'bootstrap': 'MIT',
  'tailwindcss': 'MIT',
  'chalk': 'MIT',
  'commander': 'MIT',
  'fs-extra': 'MIT',
  'moment': 'MIT',
  'dayjs': 'MIT',
  'uuid': 'MIT',
  'dotenv': 'BSD-2-Clause',
  'jest': 'MIT',
  'mocha': 'MIT',
  'eslint': 'MIT',
  'prettier': 'MIT',
  'babel-core': 'MIT',
  '@babel/core': 'MIT',
  'nodemon': 'MIT',
  'pm2': 'AGPL-3.0',
  'mongoose': 'MIT',
  'sequelize': 'MIT',
  'typeorm': 'MIT',
  'redis': 'MIT',
  'socket.io': 'MIT',
  'graphql': 'MIT',
  'apollo-server': 'MIT',
  'mongodb': 'Apache-2.0',
  'pg': 'MIT',
  'mysql': 'MIT',
  'sqlite3': 'BSD-3-Clause',
  'bcrypt': 'MIT',
  'jsonwebtoken': 'MIT',
  'passport': 'MIT',
  'cors': 'MIT',
  'helmet': 'MIT',
  'morgan': 'MIT',
  'body-parser': 'MIT',
  'cookie-parser': 'MIT',
  'multer': 'MIT',
  'sharp': 'Apache-2.0',
  'puppeteer': 'Apache-2.0',
  'cheerio': 'MIT',
  'jsdom': 'MIT',
  'node-fetch': 'MIT',
  'got': 'MIT',
  'request': 'Apache-2.0',
  'async': 'MIT',
  'bluebird': 'MIT',
  'rxjs': 'Apache-2.0',
  'immer': 'MIT',
  'recoil': 'MIT',
  'redux': 'MIT',
  'mobx': 'MIT',
  'zustand': 'MIT',
  'styled-components': 'MIT',
  'emotion': 'MIT',
  'antd': 'MIT',
  'element-ui': 'MIT',
  'material-ui': 'MIT',
  '@mui/material': 'MIT',
  'svelte': 'MIT',
  'solid-js': 'MIT',
  'remix': 'MIT',
  'sveltekit': 'MIT',
  'rollup': 'MIT',
  'esbuild': 'MIT',
  'swc': 'Apache-2.0',
  'turbo': 'MPL-2.0',
  'nx': 'MIT',
  'lerna': 'MIT',
  'yarn': 'BSD-2-Clause',
  'pnpm': 'MIT',
  'npm': 'Artistic-2.0',
};

const PIP_LICENSE_DB: Record<string, string> = {
  'django': 'BSD-3-Clause',
  'flask': 'BSD-3-Clause',
  'fastapi': 'MIT',
  'requests': 'Apache-2.0',
  'numpy': 'BSD-3-Clause',
  'pandas': 'BSD-3-Clause',
  'tensorflow': 'Apache-2.0',
  'pytorch': 'BSD-3-Clause',
  'scikit-learn': 'BSD-3-Clause',
  'scipy': 'BSD-3-Clause',
  'matplotlib': 'PSF-2.0',
  'pillow': 'MIT',
  'beautifulsoup4': 'MIT',
  'lxml': 'BSD-3-Clause',
  'selenium': 'Apache-2.0',
  'pytest': 'MIT',
  'unittest': 'Python-2.0',
  'sqlalchemy': 'MIT',
  'django-rest-framework': 'BSD-3-Clause',
  'celery': 'BSD-3-Clause',
  'redis': 'MIT',
  'pymongo': 'Apache-2.0',
  'psycopg2': 'LGPL-3.0',
  'psycopg2-binary': 'LGPL-3.0',
  'gunicorn': 'MIT',
  'uwsgi': 'GPL-2.0',
  'werkzeug': 'BSD-3-Clause',
  'jinja2': 'BSD-3-Clause',
  'click': 'BSD-3-Clause',
  'typer': 'MIT',
  'pydantic': 'MIT',
  'starlette': 'BSD-3-Clause',
  'uvicorn': 'BSD-3-Clause',
  'httpx': 'BSD-3-Clause',
  'aiohttp': 'Apache-2.0',
  'asyncio': 'Python-2.0',
  'tornado': 'Apache-2.0',
  'twisted': 'MIT',
  'pyyaml': 'MIT',
  'toml': 'MIT',
  'tomli': 'MIT',
  'configparser': 'Python-2.0',
  'python-dotenv': 'BSD-3-Clause',
  'python-dateutil': 'Apache-2.0',
  'pytz': 'MIT',
  'six': 'MIT',
  'setuptools': 'MIT',
  'pip': 'MIT',
  'virtualenv': 'MIT',
  'poetry': 'MIT',
  'pipenv': 'MIT',
  'black': 'MIT',
  'flake8': 'MIT',
  'mypy': 'MIT',
  'pylint': 'GPL-2.0',
  'bandit': 'Apache-2.0',
  'coverage': 'Apache-2.0',
  'tox': 'MIT',
  'fabric': 'BSD-2-Clause',
  'paramiko': 'LGPL-2.1',
  'cryptography': 'Apache-2.0',
  'pyopenssl': 'Apache-2.0',
  'bcrypt': 'Apache-2.0',
  'passlib': 'BSD-3-Clause',
  'jwt': 'MIT',
  'pyjwt': 'MIT',
  'oauth2client': 'Apache-2.0',
  'google-auth': 'Apache-2.0',
  'boto3': 'Apache-2.0',
  'botocore': 'Apache-2.0',
  'awscli': 'Apache-2.0',
  'azure-storage-blob': 'MIT',
  'pandasql': 'MIT',
  'openpyxl': 'MIT',
  'xlrd': 'BSD-3-Clause',
  'xlwt': 'BSD-3-Clause',
  'networkx': 'BSD-3-Clause',
  'nltk': 'Apache-2.0',
  'spacy': 'MIT',
  'transformers': 'Apache-2.0',
  'torch': 'BSD-3-Clause',
  'keras': 'Apache-2.0',
  'jupyter': 'BSD-3-Clause',
  'notebook': 'BSD-3-Clause',
  'ipython': 'BSD-3-Clause',
};

const GO_LICENSE_DB: Record<string, string> = {
  'github.com/gin-gonic/gin': 'MIT',
  'github.com/gin-contrib/cors': 'MIT',
  'github.com/gin-contrib/gzip': 'MIT',
  'github.com/gin-contrib/sessions': 'MIT',
  'github.com/golang/protobuf': 'BSD-3-Clause',
  'google.golang.org/protobuf': 'BSD-3-Clause',
  'google.golang.org/grpc': 'Apache-2.0',
  'google.golang.org/api': 'BSD-3-Clause',
  'gorm.io/gorm': 'MIT',
  'gorm.io/driver/mysql': 'MIT',
  'gorm.io/driver/postgres': 'MIT',
  'gorm.io/driver/sqlite': 'MIT',
  'github.com/jinzhu/gorm': 'MIT',
  'github.com/go-sql-driver/mysql': 'MPL-2.0',
  'github.com/lib/pq': 'MIT',
  'github.com/mattn/go-sqlite3': 'MIT',
  'github.com/go-redis/redis': 'BSD-2-Clause',
  'github.com/redis/go-redis/v9': 'BSD-2-Clause',
  'github.com/go-redis/redis/v8': 'BSD-2-Clause',
  'github.com/mediocregopher/radix': 'MIT',
  'github.com/gorilla/mux': 'BSD-3-Clause',
  'github.com/gorilla/websocket': 'BSD-2-Clause',
  'github.com/gorilla/sessions': 'BSD-3-Clause',
  'github.com/gorilla/csrf': 'BSD-3-Clause',
  'github.com/labstack/echo': 'MIT',
  'github.com/labstack/echo/v4': 'MIT',
  'github.com/fiber/fiber/v2': 'MIT',
  'github.com/gofiber/fiber/v2': 'MIT',
  'github.com/beego/beego': 'Apache-2.0',
  'github.com/beego/beego/v2': 'Apache-2.0',
  'github.com/astaxie/beego': 'Apache-2.0',
  'github.com/revel/revel': 'MIT',
  'github.com/martini-contrib/render': 'MIT',
  'github.com/go-martini/martini': 'MIT',
  'github.com/kataras/iris': 'BSD-3-Clause',
  'github.com/kataras/iris/v12': 'BSD-3-Clause',
  'github.com/valyala/fasthttp': 'MIT',
  'github.com/valyala/fasttemplate': 'MIT',
  'github.com/urfave/cli': 'MIT',
  'github.com/urfave/cli/v2': 'MIT',
  'github.com/spf13/cobra': 'Apache-2.0',
  'github.com/spf13/viper': 'MIT',
  'github.com/spf13/pflag': 'BSD-3-Clause',
  'github.com/spf13/afero': 'Apache-2.0',
  'github.com/sirupsen/logrus': 'MIT',
  'github.com/rs/zerolog': 'MIT',
  'go.uber.org/zap': 'MIT',
  'github.com/zeromicro/go-zero': 'MIT',
  'github.com/bytedance/sonic': 'Apache-2.0',
  'github.com/json-iterator/go': 'MIT',
  'github.com/tidwall/gjson': 'MIT',
  'github.com/tidwall/sjson': 'MIT',
  'github.com/tidwall/pretty': 'MIT',
  'github.com/stretchr/testify': 'MIT',
  'github.com/golang/mock': 'Apache-2.0',
  'go.uber.org/mock': 'MIT',
  'github.com/magiconair/properties': 'BSD-2-Clause',
  'github.com/pelletier/go-toml': 'MIT',
  'github.com/pelletier/go-toml/v2': 'MIT',
  'gopkg.in/yaml.v2': 'Apache-2.0',
  'gopkg.in/yaml.v3': 'MIT',
  'github.com/go-yaml/yaml': 'MIT',
  'github.com/google/uuid': 'BSD-3-Clause',
  'github.com/google/go-cmp': 'BSD-3-Clause',
  'github.com/google/gofuzz': 'Apache-2.0',
  'github.com/google/go-github': 'BSD-3-Clause',
  'github.com/hashicorp/go-uuid': 'MPL-2.0',
  'github.com/hashicorp/go-multierror': 'MPL-2.0',
  'github.com/hashicorp/errwrap': 'MPL-2.0',
  'github.com/mitchellh/mapstructure': 'MIT',
  'github.com/mitchellh/go-homedir': 'MIT',
  'github.com/mitchellh/gox': 'MPL-2.0',
  'github.com/imdario/mergo': 'BSD-3-Clause',
  'github.com/oklog/ulid': 'Apache-2.0',
  'github.com/rs/xid': 'MIT',
  'github.com/segmentio/ksuid': 'MIT',
  'github.com/teris-io/shortid': 'MIT',
  'github.com/robfig/cron': 'MIT',
  'github.com/robfig/cron/v3': 'MIT',
  'github.com/go-co-op/gocron': 'MIT',
  'github.com/olekukonko/tablewriter': 'MIT',
  'github.com/fatih/color': 'MIT',
  'github.com/mgutz/ansi': 'MIT',
  'github.com/mattn/go-colorable': 'MIT',
  'github.com/mattn/go-isatty': 'MIT',
  'github.com/shiena/ansicolor': 'Apache-2.0',
  'github.com/pkg/errors': 'BSD-2-Clause',
  'github.com/juju/errors': 'LGPL-3.0',
  'github.com/hashicorp/go-error': 'MPL-2.0',
  'github.com/cockroachdb/errors': 'Apache-2.0',
  'go.uber.org/atomic': 'MIT',
  'go.uber.org/multierr': 'MIT',
  'go.uber.org/dig': 'MIT',
  'go.uber.org/fx': 'MIT',
  'github.com/samber/lo': 'MIT',
  'github.com/thoas/go-funk': 'MIT',
  'github.com/ahmetb/go-linq': 'Apache-2.0',
  'github.com/jinzhu/now': 'MIT',
  'github.com/jinzhu/copier': 'MIT',
  'github.com/jinzhu/inflection': 'MIT',
  'github.com/shopspring/decimal': 'MIT',
  'github.com/shopspring/decimal2': 'MIT',
  'github.com/Rican7/retry': 'MIT',
  'github.com/avast/retry-go': 'MIT',
  'github.com/cenkalti/backoff': 'MIT',
  'github.com/cenkalti/backoff/v4': 'MIT',
};

export function getNpmLicense(packageName: string): string | null {
  return NPM_LICENSE_DB[packageName] || null;
}

export function getPipLicense(packageName: string): string | null {
  const lowerName = packageName.toLowerCase().replace(/_/g, '-');
  return PIP_LICENSE_DB[lowerName] || PIP_LICENSE_DB[packageName] || null;
}

export function getGoLicense(packageName: string): string | null {
  return GO_LICENSE_DB[packageName] || null;
}

export function getLicenseForPackage(
  packageName: string,
  packageManager: 'npm' | 'pip' | 'go'
): string {
  let license: string | null = null;

  switch (packageManager) {
    case 'npm':
      license = getNpmLicense(packageName);
      break;
    case 'pip':
      license = getPipLicense(packageName);
      break;
    case 'go':
      license = getGoLicense(packageName);
      break;
  }

  return license || 'UNKNOWN';
}
